import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {load} from 'cheerio';

const legalCopy=JSON.parse(fs.readFileSync(new URL('./zona-legal-copy.json',import.meta.url),'utf8'));
const domain='https://apartmanizonaorebic.com';
const locales={
 hr:{title:'Cjenik smještaja 2026.',label:'Cjenik',period:'Razdoblje boravka',current:'Cijena / noć',anchor:'Cijena 10.9.2026. / noć',short:'Cijena 10.9.2026.',from:'od',night:'/ noć',home:'Početna',all:'Cjenik i preuzimanje',intro:'Pregled cijena za svih šest smještajnih jedinica. Iznosi su u eurima po smještajnoj jedinici i noći, za navedeno razdoblje boravka u 2026. godini.',explain:'Dodatna (sidrena) cijena prikazuje redovnu cijenu iz cjenika važećeg 10.9.2026. za istu jedinicu i navedeno razdoblje boravka, bez akcijskih popusta. To je usporedni podatak, a ne druga cijena za plaćanje.',past:'Ranija razdoblja iz 2026. ostaju prikazana kao dio sezonskog cjenika; nisu ponuda za prošle datume. Za druge termine i 2027. godinu zatražite ponudu.',download:'Preuzmi',machine:'Digitalni cjenik (HR)',archive:'Arhiva cjenika',archiveNote:'Prethodne objavljene verzije ostaju javno dostupne najmanje 30 dana. Za aktualnu ponudu koristite najnoviju verziju.',version:'Verzija',prepared:'Pripremljeno',terms:'Uvjeti i usporedba cijena',unit:'Pogledaj smještaj',enquiry:'Pošalji upit',min:'Minimalni boravak: 3 noći. Konačnu cijenu i raspoloživost potvrđuje domaćin prije rezervacije.',unchanged:'Redovne cijene, bez akcijskog popusta.',description:'Cjenik Apartmana Zona u Orebiću za 2026.: cijene po noći, usporedne cijene iz cjenika od 10.9.2026., CSV/XML preuzimanje i arhiva.'},
 en:{title:'Accommodation rates 2026',label:'Rates',period:'Stay period',current:'Rate / night',anchor:'Rate on 10 Sep 2026 / night',short:'Rate on 10 Sep 2026',from:'from',night:'/ night',home:'Home',all:'Rates and downloads',intro:'Rates for all six accommodation units. Prices are in euros per accommodation unit per night, for the stated stay period in 2026.',explain:'The additional reference rate is the regular rate listed on 10 September 2026 for the same unit and stated stay period, excluding promotional discounts. It is a comparison figure, not a second amount to pay.',past:'Earlier periods in 2026 remain part of the seasonal price list; they are not offers for past dates. Please request a quote for other dates and for 2027.',download:'Download',machine:'Digital price list (Croatian)',archive:'Price list archive',archiveNote:'Previous published versions remain publicly available for at least 30 days. Use the latest version for current rates.',version:'Version',prepared:'Prepared',terms:'Conditions and rate comparison',unit:'View accommodation',enquiry:'Send an enquiry',min:'Minimum stay: 3 nights. The host confirms the final price and availability before booking.',unchanged:'Regular rates, without promotional discounts.',description:'Apartmani Zona Orebić rates for 2026: nightly rates, reference rates from 10 September 2026, CSV/XML downloads and price list archive.'},
 de:{title:'Unterkunftspreise 2026',label:'Preisliste',period:'Aufenthaltszeitraum',current:'Preis / Nacht',anchor:'Preis am 10.9.2026 / Nacht',short:'Preis am 10.9.2026',from:'ab',night:'/ Nacht',home:'Startseite',all:'Preisliste und Downloads',intro:'Preise für alle sechs Unterkünfte. Alle Beträge gelten in Euro pro Unterkunft und Nacht für den angegebenen Aufenthaltszeitraum im Jahr 2026.',explain:'Der zusätzliche Referenzpreis ist der reguläre Preis laut der am 10.9.2026 gültigen Preisliste für dieselbe Unterkunft und denselben Aufenthaltszeitraum, ohne Aktionsrabatte. Er dient dem Vergleich und ist kein zusätzlicher Zahlbetrag.',past:'Frühere Zeiträume aus 2026 bleiben Teil der Saisonpreisliste; sie sind keine Angebote für vergangene Termine. Für andere Termine und 2027 bitten wir um eine Anfrage.',download:'Herunterladen',machine:'Digitale Preisliste (Kroatisch)',archive:'Preislistenarchiv',archiveNote:'Frühere veröffentlichte Versionen bleiben mindestens 30 Tage öffentlich zugänglich. Für aktuelle Preise verwenden Sie die neueste Version.',version:'Version',prepared:'Erstellt',terms:'Bedingungen und Preisvergleich',unit:'Unterkunft ansehen',enquiry:'Anfrage senden',min:'Mindestaufenthalt: 3 Nächte. Der Gastgeber bestätigt den Endpreis und die Verfügbarkeit vor der Buchung.',unchanged:'Reguläre Preise ohne Aktionsrabatt.',description:'Preisliste der Apartmani Zona in Orebić für 2026: Nachtpreise, Referenzpreise vom 10.9.2026, CSV/XML-Downloads und Archiv.'},
 cs:{title:'Ceník ubytování 2026',label:'Ceník',period:'Termín pobytu',current:'Cena / noc',anchor:'Cena k 10.9.2026 / noc',short:'Cena k 10.9.2026',from:'od',night:'/ noc',home:'Úvod',all:'Ceník a stažení',intro:'Ceny všech šesti ubytovacích jednotek. Částky jsou uvedeny v eurech za celou jednotku a noc pro uvedený termín pobytu v roce 2026.',explain:'Doplňková referenční cena je běžná cena z ceníku platného 10.9.2026 pro stejnou jednotku a uvedený termín pobytu, bez akčních slev. Slouží ke srovnání, nejde o další částku k úhradě.',past:'Dřívější termíny roku 2026 zůstávají součástí sezónního ceníku; nejsou nabídkou pobytu v minulosti. Pro jiné termíny a rok 2027 si vyžádejte nabídku.',download:'Stáhnout',machine:'Digitální ceník (chorvatsky)',archive:'Archiv ceníků',archiveNote:'Předchozí zveřejněné verze zůstávají veřejně dostupné nejméně 30 dní. Aktuální ceny najdete v nejnovější verzi.',version:'Verze',prepared:'Připraveno',terms:'Podmínky a porovnání cen',unit:'Zobrazit ubytování',enquiry:'Odeslat poptávku',min:'Minimální pobyt: 3 noci. Konečnou cenu a dostupnost potvrdí hostitel před rezervací.',unchanged:'Běžné ceny bez akčních slev.',description:'Ceník Apartmani Zona v Orebići pro rok 2026: ceny za noc, referenční ceny k 10.9.2026, soubory CSV/XML a archiv.'},
 pl:{title:'Cennik noclegów 2026',label:'Cennik',period:'Termin pobytu',current:'Cena / noc',anchor:'Cena z 10.9.2026 / noc',short:'Cena z 10.9.2026',from:'od',night:'/ noc',home:'Strona główna',all:'Cennik i pliki',intro:'Ceny wszystkich sześciu jednostek noclegowych. Kwoty podano w euro za całą jednostkę i noc, dla wskazanego terminu pobytu w 2026 roku.',explain:'Dodatkowa cena odniesienia to regularna cena z cennika obowiązującego 10.9.2026 dla tej samej jednostki i wskazanego terminu pobytu, bez rabatów promocyjnych. Służy porównaniu, nie jest dodatkową kwotą do zapłaty.',past:'Wcześniejsze terminy z 2026 roku pozostają częścią sezonowego cennika; nie są ofertą na minione daty. Zapytaj o wycenę na inne terminy i rok 2027.',download:'Pobierz',machine:'Cennik cyfrowy (po chorwacku)',archive:'Archiwum cenników',archiveNote:'Poprzednie opublikowane wersje pozostają publicznie dostępne przez co najmniej 30 dni. Aktualne ceny znajdują się w najnowszej wersji.',version:'Wersja',prepared:'Przygotowano',terms:'Warunki i porównanie cen',unit:'Zobacz nocleg',enquiry:'Wyślij zapytanie',min:'Minimalny pobyt: 3 noce. Gospodarz potwierdza ostateczną cenę i dostępność przed rezerwacją.',unchanged:'Ceny regularne, bez rabatu promocyjnego.',description:'Cennik Apartmani Zona w Orebiću na 2026 rok: ceny za noc, ceny odniesienia z 10.9.2026, pliki CSV/XML i archiwum.'}
};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prefix=l=>l==='hr'?'/':`/${l}/`;
const route=l=>prefix(l)+'cjenik/';
const digest=s=>createHash('sha256').update(s).digest('hex');
const day=s=>s.slice(8,10)+'.'+s.slice(5,7)+'.'+s.slice(0,4)+'.';
const period=p=>`${day(p.from)} – ${day(p.to)}`;
const money=(n,l)=>new Intl.NumberFormat(l,{style:'currency',currency:'EUR',minimumFractionDigits:2}).format(n);
const write=(root,p,s)=>{const file=path.join(root,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,s);};
export function validatePrices(data){
 assert(Number.isInteger(data.revision)&&data.revision>0,'Positive revision required');
 assert.equal(data.referenceDate,'2026-09-10');assert.equal(data.currency,'EUR');
 assert.equal(data.allMandatoryChargesIncluded,true,'Review included-charge copy before changing charge policy');
 assert.equal(data.specialSale,false,'Promotional prices require separate legal review and display');assert.equal(data.specialSaleName,'');
 assert.equal(data.units.length,6);assert.equal(new Set(data.units.map(u=>u.id)).size,6);
 assert.equal(data.periods.length,3);
 for(const p of data.periods){assert(/^\d{4}-\d{2}-\d{2}$/.test(p.from)&&p.from<=p.to);assert.equal(new Date(p.from).toISOString().slice(0,10),p.from);assert.equal(new Date(p.to).toISOString().slice(0,10),p.to);}
 for(const u of data.units){assert(/^[a-z0-9]+$/.test(u.id));for(const key of ['prices','referencePrices']){assert.equal(u[key].length,data.periods.length);u[key].forEach(n=>assert(Number.isFinite(n)&&n>0&&Number.isInteger(n*100),'Missing or invalid confirmed rate'));}}
}
export function makeExports(data){
 const keys=['naziv_usluge','maloprodajna_cijena','posebni_oblik_prodaje','naziv_posebnog_oblika_prodaje','sidrena_cijena','valuta','obracunska_jedinica','referentni_datum','razdoblje_boravka_od','razdoblje_boravka_do','oznaka_jedinice','ukljuceni_troskovi'];
 const rows=data.units.flatMap(u=>data.periods.map((p,i)=>[`${u.name} — ${period(p)}`,u.prices[i].toFixed(2),'NE','',u.referencePrices[i].toFixed(2),data.currency,data.unit,data.referenceDate,p.from,p.to,u.id,data.includedCharges]));
 const csv='\uFEFF'+[keys,...rows].map(row=>row.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\r\n')+'\r\n';
 const xml='<?xml version="1.0" encoding="UTF-8"?>\n<cjenik verzija="'+data.revision+'"><objekt><naziv>Apartmani Zona Orebić</naziv><adresa>'+escape(data.address)+'</adresa><oznaka>'+escape(data.objectCode)+'</oznaka></objekt><usluge>'+rows.map(row=>'<usluga>'+keys.map((key,i)=>`<${key}>${escape(row[i])}</${key}>`).join('')+'</usluga>').join('\n')+'</usluge></cjenik>\n';
 return {csv,xml,rows};
}
export function renderPrices(root, data=JSON.parse(fs.readFileSync(new URL('./zona-prices.json',import.meta.url),'utf8'))){
 root=path.resolve(root);validatePrices(data);
 const manifestPath=path.join(root,'cjenik/arhiva/manifest.json');
 const manifest=fs.existsSync(manifestPath)?JSON.parse(fs.readFileSync(manifestPath,'utf8')):[];
 const fingerprint=digest(JSON.stringify(data));
 let release=manifest.find(r=>r.revision===data.revision);
 if(release)assert.equal(release.fingerprint,fingerprint,'Published revision is immutable: increment revision instead of overwriting history');
 else{assert(!manifest.length||data.revision>Math.max(...manifest.map(r=>r.revision)),'Revision must increase');const at=new Date().toISOString();release={revision:data.revision,publishedAt:at,fingerprint,stem:`smjestaj_Josipa-bana-Jelacica-24-20250-Orebic_${data.objectCode}_${String(data.revision).padStart(4,'0')}_${at.replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}`};manifest.push(release);}
 const files=makeExports(data);
 for(const ext of ['csv','xml']){const rel=`cjenik/arhiva/${release.stem}.${ext}`,existing=path.join(root,rel);if(fs.existsSync(existing))assert.equal(fs.readFileSync(existing,'utf8'),files[ext],'Refusing to overwrite archived prices');else write(root,rel,files[ext]);write(root,`cjenik/aktualni.${ext}`,files[ext]);}
 const snapshot=`cjenik/arhiva/${release.stem}.json`;
 if(!fs.existsSync(path.join(root,snapshot)))write(root,snapshot,JSON.stringify(data,null,2)+'\n');
 write(root,'cjenik/arhiva/manifest.json',JSON.stringify(manifest,null,2)+'\n');
 const css=fs.readFileSync(new URL('./zona-prices.css',import.meta.url),'utf8');
 const cssPath='/assets/zona-prices-'+digest(css).slice(0,12)+'.css';write(root,cssPath,css);
 const table=(u,l)=>{const c=locales[l];return `<table class="price-table" aria-label="${escape(u.name)}"><thead><tr><th scope="col">${c.period}</th><th scope="col">${c.current}</th><th scope="col">${c.anchor}</th></tr></thead><tbody>${data.periods.map((p,i)=>`<tr data-period="${p.from}"><td>${period(p)}</td><td>${money(u.prices[i],l)}</td><td class="reference-price">${money(u.referencePrices[i],l)}</td></tr>`).join('')}</tbody></table>`;};
 for(const [l,c] of Object.entries(locales)){
  c.included=legalCopy[l].allInclusive;
  const pre=prefix(l),homeFile=path.join(root,pre,'index.html');const q=load(fs.readFileSync(homeFile,'utf8'));
  const titles={};
  for(const u of data.units){const d=q('#dialog-'+u.id);assert.equal(d.length,1,'Missing accommodation '+u.id);titles[u.id]=d.find('h2').first().text();d.find('.price-table').replaceWith(table({...u,name:titles[u.id]},l));d.find('.anchor-explanation,.prices-link,.included-charges').remove();d.find('.price-table').after(`<p class="included-charges">${c.included}</p><p class="anchor-explanation">${c.explain}</p><a class="prices-link" href="${route(l)}#rates-${u.id}">${c.all} →</a>`);
   const card=q('#unit-'+u.id);card.find('.price-reference').remove();const idx=u.prices.indexOf(Math.min(...u.prices));card.find('.price strong').text(money(u.prices[idx],l));card.find('.card-bottom').append(`<p class="price-reference">${c.short}: <strong>${c.from} ${money(u.referencePrices[idx],l)}</strong> ${c.night}<br><a href="${route(l)}#rates-${u.id}">${c.all} →</a></p>`);
  }
  const lead=q('.unit-head .section-lead');lead.find('.prices-link').remove();lead.html(lead.html().trimEnd());lead.append(` <a class="prices-link" href="${route(l)}">${c.all} →</a>`);
  const addCommon=(dom)=>{dom('link[href*="/assets/zona-prices-"]').remove();dom('head').append(`<link rel="stylesheet" href="${cssPath}">`);dom('.footer .copy a[data-price-link]').remove();dom('.footer .copy').append(`<a data-price-link href="${route(l)}">${c.label}</a>`);};
  addCommon(q);write(root,pre+'index.html',q.html());
  for(const page of ['privacy','thank-you','uvjeti'].filter(page=>fs.existsSync(path.join(root,pre,page,'index.html')))){const f=path.join(root,pre,page,'index.html');const dom=load(fs.readFileSync(f,'utf8'));addCommon(dom);write(root,pre+page+'/index.html',dom.html());}
  const p=load(q.html());p('.topline,dialog,.float-wa').remove();p('.header').addClass('subpage-header');
  p('.header a[href^="#"],footer a[href^="#"]').each((_,e)=>p(e).attr('href',pre+p(e).attr('href')));p('a.logo').attr('href',pre);
  p('.lang-switch').each((_,e)=>p(e).attr('href',route(p(e).attr('lang'))));
  const downloads=ext=>`/cjenik/arhiva/${release.stem}.${ext}`;
  p('main').html(`<section class="section shell price-page"><a class="price-back" href="${pre}">← ${c.home}</a><div class="eyebrow">APARTMANI ZONA · OREBIĆ</div><h1>${c.title}</h1><p class="price-intro">${c.intro}</p><p class="included-charges">${c.included}</p><p class="price-meta">${escape(data.address)}<br>${c.version} ${data.revision} · ${c.prepared}: ${new Intl.DateTimeFormat(l,{dateStyle:'long',timeZone:'Europe/Zagreb'}).format(new Date(release.publishedAt))}</p><div class="price-downloads"><a class="btn gold" download href="${downloads('csv')}">${c.download} CSV ↓</a><a class="btn ghost" download href="${downloads('xml')}">${c.download} XML ↓</a><a class="btn ghost" href="${pre}#contact">${c.enquiry} →</a></div><p class="price-meta">${c.machine} · EUR · ${c.unchanged}</p><div class="price-info"><h2>${c.terms}</h2><p>${c.explain}</p><p>${c.min}</p><p><a href="${pre}uvjeti/">${legalCopy[l].termsLabel}</a></p></div><p class="price-past-note">${c.past}</p><div class="price-unit-grid">${data.units.map(u=>`<section class="price-unit" id="rates-${u.id}"><h2>${escape(titles[u.id])}</h2>${table({...u,name:titles[u.id]},l)}<p>${c.unchanged}</p><a href="${pre}#unit-${u.id}">${c.unit} →</a></section>`).join('')}</div><section class="price-archive" id="archive"><h2>${c.archive}</h2><p>${c.archiveNote}</p><ul>${[...manifest].reverse().map(r=>`<li>${c.version} ${r.revision} · ${new Intl.DateTimeFormat(l,{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Zagreb'}).format(new Date(r.publishedAt))} — <a href="/cjenik/arhiva/${r.stem}.csv">CSV</a> / <a href="/cjenik/arhiva/${r.stem}.xml">XML</a></li>`).join('')}</ul></section></section>`);
  p('title').text(c.title+' | Apartmani Zona Orebić');p('meta[name="description"]').attr('content',c.description);p('link[rel="canonical"]').attr('href',domain+route(l));p('meta[property="og:url"]').attr('content',domain+route(l));
  for(const key of ['og:title','twitter:title'])p(`meta[property="${key}"],meta[name="${key}"]`).attr('content',c.title+' | Apartmani Zona Orebić');for(const key of ['og:description','twitter:description'])p(`meta[property="${key}"],meta[name="${key}"]`).attr('content',c.description);
  p('link[hreflang]').each((_,e)=>{const lang=p(e).attr('hreflang');p(e).attr('href',domain+route(lang==='x-default'?'hr':lang));});
  p('script[type="application/ld+json"]').remove();p('head').append(`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage','@id':domain+route(l)+'#webpage',url:domain+route(l),name:c.title,inLanguage:l,isPartOf:{'@id':domain+'/#website'},about:{'@id':domain+'/#lodging'}})}</script>`);
  p('head').append(`<link rel="alternate" type="text/csv" title="CSV" href="/cjenik/aktualni.csv"><link rel="alternate" type="application/xml" title="XML" href="/cjenik/aktualni.xml">`);
  write(root,route(l)+'index.html',p.html());
 }
 const sm=load(fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'),{xml:true});sm('url').each((_,e)=>{if(sm(e).find('loc').text().endsWith('/cjenik/'))sm(e).remove();});for(const l of Object.keys(locales))sm('urlset').append(`<url><loc>${domain+route(l)}</loc><lastmod>${release.publishedAt.slice(0,10)}</lastmod></url>`);write(root,'sitemap.xml',sm.xml());
 let headers=fs.readFileSync(path.join(root,'_headers'),'utf8').replace(/\n# Price list exports[\s\S]*$/,'');headers+=`\n# Price list exports: public machine access, fresh current aliases, permanent history.\n/cjenik/aktualni.csv\n  Content-Type: text/csv; charset=utf-8\n  Cache-Control: public, max-age=0, must-revalidate\n  X-Robots-Tag: noindex, follow\n/cjenik/aktualni.xml\n  Content-Type: application/xml; charset=utf-8\n  Cache-Control: public, max-age=0, must-revalidate\n  X-Robots-Tag: noindex, follow\n/cjenik/arhiva/*\n  Cache-Control: public, max-age=0, must-revalidate\n  X-Robots-Tag: noindex, follow\n`;write(root,'_headers',headers);
 return {revision:data.revision,rows:files.rows.length,pricePages:5,referenceDate:data.referenceDate,archive:release.stem};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(renderPrices(process.argv[2]||fileURLToPath(new URL('../',import.meta.url))),null,2));
